### ISSUE TITLE
what disks do i need in the server for this servers setup?

### ISSUE THREAD

**Issue by virtuman** [iMelnik/hetzner-docker#5]
This looks like what I'm trying to set up but could you please clarify, what disk setup did you have in mind for this installation instructions? 

Our hetzner servers have 2 * SSD disks, and previously I used to set it up in RAID1, but I lost a complete node yesterday due to CENTOS + devicemapper / loopback volume and I now tend to think that disks do not need to be set up in the RAID but instead - one disk for system files and another disk should be fully dedicated for docker data and spread redundancy across multiple nodes, rather than raid1?

What are your recommendations? Have you tried Ubuntu 16.x with the same setup image? Any comments on this distro?

**Comment by iMelnik** [comment]
Hi @virtuman 
Setup files can be modified depending on your needs, have a look at [do-install-trusty.sh](https://github.com/iMelnik/hetzner-docker/blob/master/do-install-trusty.sh)
In most of our setups, we stick with mdraid like: ```SWRAID 1 SWRAIDLEVEL 1```  for the system drives and add more drives for data. Anyway - redundancy is not backup.
I cannot say anything about 16.04 - did not try it yet.

**Comment by virtuman** [comment]
Thank you for quick reply.

Just to clarify - you have RAID 1 on system and extra 1 drive for docker data or 1 for docker? what linux distress and volume drivers have you used in production successfully? 
AUFS
Overlay
device mapper
BTRFS


Any previous experience with CentOS 7 ? would you recommend or not recommend using it as the host system?

**Comment by iMelnik** [comment]
Most of our systems are Ubuntu 14.04 based, but we have some CentOS 6 boxes running.
All the data is not stored within docker hosts but accessed over the network.
Docker hosts use devicemapper/Overlay but they have no local volumes or heavy IO
